### PR TITLE
Fix Too much recursion error

### PR DESCRIPTION
**Pull request by jotak**
Need to update the groups after scope is changed, not just from the options panel

### CODE REVIEW

**Comment by jotak** [comment]
By the way, I found how to reproduce consistently.
With any active filters, in the topology view, do:
1. Set scope = owner
2. Open the topology options panel
3. Set groups = namespaces
4. Close the options panel
5. Set scope = namespace

Note that the bug is only when you close the option panel; if you keep it opened, it was working fine.

**Review by jpinsonneau — CHANGES_REQUESTED** [review]
Your case works fine, thanks !

However I'm still able to make it crash because of the same issue but with a different approach:

1. set scope = owner or resource & group = namespace
2. go to `overview` tab
3. set scope to `namespace`
4. go to `topology` tab

**Comment by jotak** [comment]
> However I'm still able to make it crash because of the same issue but with a different approach:

Yeah that's exactly why I put on hold, I noticed that as well :)

**Comment by jotak** [comment]
@jpinsonneau fixed for overview page.
BTW let me know if it's ok with you: I changed the algo so that it removes any groups when it's invalid, rather than finding the last available one. The reason is I find it weird when I grouped by namespace, to have it switched to node groups -- which I don't really care about.

**Comment by jpinsonneau** [comment]
I'm fine with the new behavior as it doesn't affect `stepInto` one.

However, now I'm getting rendering issues when I try to reproduce on local using console bridge:
image

**Comment by jotak** [comment]
@jpinsonneau I've seen this issue as well, but not in this PR, I don't know what is causing it but I'm wondering if it's not a separate problem? Any idea?

**Comment by jotak** [comment]
@jpinsonneau I see the same issue on `main`:
Capture d’écran du 2022-10-13 21-45-36

I've no idea where this regression comes from ... my previous PR? but I don't see what wrong I could have done? Or maybe a regression after your last upgrade of sdk/patternfly?

**Comment by jotak** [comment]
cc @andrew-ronaldson : looking at the screenshots above, are you aware of a known issue in patternfly?

**Comment by jpinsonneau** [comment]
> @jpinsonneau I see the same issue on `main`

Well it probably comes from the update in that case. I feel an optimisation has been made to keep either source / destination ids or even coordinates.
I just pushed a fix that forces graph reset on group change https://github.com/netobserv/network-observability-console-plugin/pull/207/commits/96935823a520c05b9cf09c8d46900cec0f29d0c8

It works ! the only downside is a small loss of performances since everything is redrawn from scratch but we already do that for scope change so that's fine.

**Comment by jotak** [comment]
thanks @jpinsonneau 
/approve

**Pull request merged**
