### PR TITLE
NETOBSERV-1353 Console plugin feedback

### PR DESCRIPTION
**Pull request by jpinsonneau**
## Description

DSCP, ICMP Type, ICMP Code
- [X] as separate columns 
- [X] as separate filters

Since ICMP values overlap between IPV4 / V6 and Types, I decided to not suggest dropdown options for theses.

## Dependencies

n/a

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [x] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [x] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Review by OlivierCazade — APPROVED** [review]
LGTM, thanks!

**Comment by jpinsonneau** [comment]
Fixed tests: https://github.com/netobserv/network-observability-console-plugin/pull/423/commits/100b6a9d6cf70ed8f90cdaef83111484a616fe55

FYI side panel will not show `n/a` fields anymore as we are starting to have too many fields. Each field will show up as soon as a relevent value is available.

**Comment by jpinsonneau** [comment]
Following @Amoghrd feedback, the ICMP type & code will show in red when protocol is not ICMP

image

**Pull request merged**
