### PR TITLE
NETOBSERV-1337 DSCP filter & side panel details

### PR DESCRIPTION
**Pull request by jpinsonneau**
## Description

Add DSCP
- [X] Filter
- [X] Side panel details in `Protocol` field as same as ICMP. 
  We can rename / move if necessary.

image
image

[A followup](https://issues.redhat.com/browse/NETOBSERV-1353) will contains the following changes:
- Graph requires https://github.com/netobserv/network-observability-console-plugin/pull/389
- Table column (not sure it's needed here)
- Quick filter dropdown

## Dependencies

https://github.com/netobserv/netobserv-ebpf-agent/pull/158
https://github.com/netobserv/flowlogs-pipeline/pull/503

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [x] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [x] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Comment by Amoghrd** [comment]
@jpinsonneau The branch still shows out-of-date with master, should it be rebased with master to get the duplicate field added to labels change or is it fine?

**Comment by jpinsonneau** [comment]
> @jpinsonneau The branch still shows out-of-date with master, should it be rebased with master to get the duplicate field added to labels change or is it fine?

It's the async overview; it's not related you can go ahead with the current version :wink:

**Comment by Amoghrd** [comment]
@jpinsonneau Question regarding the DSCP value filter. Even though there is DSCP related info present under Protocol section in the side panel, there is no filter button present, is this deliberate? I am asking since all other filters have a filter button too next to them in the side panel

**Comment by jpinsonneau** [comment]
> @jpinsonneau Question regarding the DSCP value filter. Even though there is DSCP related info present under Protocol section in the side panel, there is no filter button present, is this deliberate? I am asking since all other filters have a filter button too next to them in the side panel

You should have filter button next to "Protocol" field but indeed it filter on protocol and not on DSCP.
I'll add a dropdown in the same style as topology ones that allows to select multiple options (Source / Dest)

**Comment by jpinsonneau** [comment]
> @jpinsonneau The above dropdown style for DSCP will be implemented in this PR or a later PR?

As you prefer :smile_cat: what is the easiest for you ?
- If you want to test all at one I can add both graphs and dropdown in the same PR.
- If you already tested this and wait for me we can just merge as is and I'll open a followup

**Comment by jpinsonneau** [comment]
Created a followup for graphs & dropdown:
https://issues.redhat.com/browse/NETOBSERV-1353

**Comment by jpinsonneau** [comment]
Thanks @Amoghrd @msherif1234 !

**Pull request merged**
