### PR TITLE
NETOBSERV-267 Panels & columns popup filters

### PR DESCRIPTION
**Pull request by jpinsonneau**
## Description

Add view filters to quickly pick panels / columns:
image
image

## Dependencies

Panel ids are updated in https://github.com/netobserv/network-observability-console-plugin/pull/412

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [X] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [X] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Comment by jotak** [comment]
I have a few remarks but I'm fine if you want to address them in a follow-up:

- the clickable area on the chip filters is narrowed to just the text, instead of the whole button. It makes it sometimes difficult to clic
image

- some of the chips show no result when they're related to disabled features, like DNS or Drops

Otherwise, code lgtm!

**Comment by jpinsonneau** [comment]
> I have a few remarks but I'm fine if you want to address them in a follow-up:
> 
> * the clickable area on the chip filters is narrowed to just the text, instead of the whole button. It makes it sometimes difficult to clic
>   image
> * some of the chips show no result when they're related to disabled features, like DNS or Drops
> 
> Otherwise, code lgtm!

Thanks for testing, I'll take the necessary time to improve before merging :+1:

**Comment by jpinsonneau** [comment]
@jotak I rebased and took the opportunity to improve from your feedback:
- the entire chip is now clickable
- the chips not matching to any column are not showing

Let me know if that works for you ! Thanks

**Comment by jotak** [comment]
/lgtm
thanks!

**Pull request merged**
