### PR TITLE
NETOBSERV-779 topology view crashes when layout display changed to Grid

### PR DESCRIPTION
**Pull request by jpinsonneau**
Updated cypress and PF dependencies (including https://github.com/patternfly/patternfly-react/pull/8761)
Fixed cypress tests
Moved to typescript

image

### CODE REVIEW

**Comment by jpinsonneau** [comment]
https://github.com/patternfly/patternfly-react/issues/8659

**Comment by jpinsonneau** [comment]
https://github.com/patternfly/patternfly-react/pull/8761

**Comment by Amoghrd** [comment]
@jpinsonneau Still seeing crashes when changing groups are changed when animation is still running. Changing the layout when the animation is running does not seems to lead to crashes

**Comment by memodi** [comment]
> @jpinsonneau Still seeing crashes when changing groups are changed when animation is still running. Changing the layout when the animation is running does not seems to lead to crashes

@Amoghrd - could you share screen recordings if this is being reproduced conistently? I just ran entire topology test suite  it runs successfully with no crashes (ran multiple times). The tests itself require some modifications for routes URL, I'll create a PR for it.

**Review by jotak — APPROVED** [review]

**Pull request merged**
