### PR TITLE
NETOBSERV-1214 & NETOBSERV-1399 Manage cluster name and zones

### PR DESCRIPTION
**Pull request by jpinsonneau**
## Description

Manage cluster name: `K8S_ClusterName`
- [x] Column
- [x] Filter with autocomplete
- [x] Topology aggregation and groups

Manage zone: `SrcK8S_Zone` / `DstK8S_Zone`
- [x] Columns
- [x] Filters with autocomplete
- [x] Topology aggregation and groups

image

## Dependencies

https://github.com/netobserv/network-observability-operator/pull/546

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [x] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [x] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Comment by jpinsonneau** [comment]
Following to [this feedback](https://github.com/netobserv/network-observability-operator/pull/546#discussion_r1470763017) I've adapted columns to be filtered using a new `feature` optionnal column.

See https://github.com/netobserv/network-observability-console-plugin/pull/462/commits/a52607af47f11c3e2699658fd8b194576571e631

We'll need to do the same for panels in https://github.com/netobserv/network-observability-console-plugin/pull/431

**Comment by OlivierCazade** [comment]
I did not test it, but if both zone and multi cluster enabled, there is the possibility to have nodes from different clusters in the same zone.

Is it going to work?

**Comment by jpinsonneau** [comment]
> I did not test it, but if both zone and multi cluster enabled, there is the possibility to have nodes from different clusters in the same zone.
> 
> Is it going to work?

Yes however, zones from different clusters will be mixed into the same metric in overview, if you don't filter on a specific cluster. There is no possibility to show per cluster + zone in the overview section yet.

In the table you will see both clusters but I guess that's good as is.

On topology side, the groups will be separated only if you set `Cluster + Zones`. See `addPossibleGroups` function:
https://github.com/jpinsonneau/network-observability-console-plugin/blob/8f2df29d1a3f76f4645501bf15e71cf2b17675ee/web/src/model/topology.ts#L496-L524

**Comment by jotak** [comment]
That's awesome to see traffic across zones
Love it :-)

image

/lgtm

**Pull request merged**
