### PR TITLE
Follow-up on #239: do not truncate on tooltips..

### PR DESCRIPTION
**Pull request by jotak**
.. except in side-panel metrics, where less space is available

### CODE REVIEW

**Comment by jpinsonneau** [comment]
Do you expect such overflow with this approach ?
image
image
The `openshift` contents are really long names ...

I'm not sure we should have different rules between `Overview` & `Topology` graphs :thinking: @andrew-ronaldson any thoughts on that ?

**Comment by jotak** [comment]
@jpinsonneau did you reduce your window in your screenshot? In all the tests I did, it was always displayed fine (and I think I've a smaller screen than yours :) )

**Comment by jotak** [comment]
On the different rules between overview and topology side panel, the reason is simply that _in general_ side panel charts are smaller, unlike overview charts, so it's safer to display the whole text in overview charts.

**Comment by jpinsonneau** [comment]
> @jpinsonneau did you reduce your window in your screenshot? In all the tests I did, it was always displayed fine (and I think I've a smaller screen than yours :) )

I'm using half screen size (since I'm on an ultrawide) wich result in following body size:
image
and page size (drawer open):
image

**Comment by jpinsonneau** [comment]
/approve

Ok let's merge as is.
FYI as far as I see the labels are smaller and styling a bit different in console dashboards. I'll check if we can improve this that way :+1: 

Thanks @jotak

**Pull request merged**
