### PR TITLE
NETOBSERV-1649: Improve UX and cases managed with prometheus

### PR DESCRIPTION
**Pull request by jotak**
- Automatically switch to PktDropBytes/Packets metrics when there's a drop cause/state filter
- Make topology queries less strict on fetching drops for decoration: an error will not break the whole thing anymore
  - Display warning when that happens
- small refactoring related to warning message and details

## Dependencies

n/a

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [x] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [x] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Comment by jotak** [comment]
(rebased)

**Comment by memodi** [comment]
@jotak - with this PR it looks good overall,  can you clarify what do you mean when you say?

> Automatically switch to PktDropBytes/Packets metrics when there's a drop cause/state filter

 is it to say we'll display dropped bytes/packets on topology edges when there's a match drop cause/state filter? 


image

no topology view since drop state didn't match probably?:

image

**Comment by jotak** [comment]
> @jotak - with this PR it looks good overall, can you clarify what do you mean when you say?
> 
> > Automatically switch to PktDropBytes/Packets metrics when there's a drop cause/state filter
> 
> is it to say we'll display dropped bytes/packets on topology edges when there's a match drop cause/state filter?
> 

Yes ... and while saying this, I realize this is probably not correct, at least not in every case.. Argh! Need to think more about that


> no topology view since drop state didn't match probably?:
> 

I guess yes. A way to confirm this is to install loki and switch between forced Loki / Prom datasources

**Comment by memodi** [comment]
SGTM. thanks! I'll add comment for [NETOBSERV-1740](https://issues.redhat.com/browse/NETOBSERV-1740)
/label qe-approved

**Comment by jotak** [comment]
(rebased)

**Comment by jotak** [comment]
thanks @jpinsonneau  .. sorry for the conflicts 😨
I want to merge it to fix some issues for my workshop

**Pull request merged**
