### PR TITLE
NETOBSERV-591 Build QuerySummary from metrics

### PR DESCRIPTION
**Pull request by jpinsonneau**
This brings Query Summary for Overview / Topology tabs
- Cardinality is built from available metrics (depends on scope) for top X items
- Results shows either bytes or packets of:
  - top X metrics against overall in Overview 
  - top X metrics in Topology

image
image

### CODE REVIEW

**Comment by mariomac** [comment]
I tried it and seemed to work but I don't understand what is this functionality for. What is a "metric" here?. In my case, I just get a bunch of namespaces (no Pods, no IPs, no Nodes... as in the PR screenshot):
image

**Comment by jpinsonneau** [comment]
> I tried it and seemed to work but I don't understand what is this functionality for. What is a "metric" here?. In my case, I just get a bunch of namespaces (no Pods, no IPs, no Nodes... as in the PR screenshot)

Console plugin can run 2 types of Loki queries:
- [/loki/api/v1/query](https://grafana.com/docs/loki/latest/api/#query-loki) that returns records for table view
- [/loki/api/v1/query_range](https://grafana.com/docs/loki/latest/api/#query-loki-over-a-range-of-time) that returns metrics over time

The second case was not covered by `Query Summary`. 
According to the selected scope, the metrics are more of less detailed. That's why you get only `Namespaces` in your test. If you move to `Resource` scope, you will see some pods / ips.

Does it makes sense for you ? Do you feel we should add a mention about the scope in the side panel ?

**Review by mariomac — APPROVED** [review]
@jpinsonneau I think this can be done as part of another task but I feel the "Cardinality" or "metric" concept here is not very intuitive, so probably we need to reword/document this. Also yeah I'd try to find some way to relate this with the Scope.

**Comment by jotak** [comment]
@mariomac @jpinsonneau on the "what's a metric" discussion, I would say in this context it is the Top X peer-to-peer traffic volume, in bytes or packet per second.

**Pull request merged**
