### PR TITLE
NETOBSERV-1319 single graph focus

### PR DESCRIPTION
**Pull request by jpinsonneau**
## Description

Focus on a single graph for better display:
image
image

[Screencast from 2023-10-06 16-56-35.webm](https://github.com/netobserv/network-observability-console-plugin/assets/91894519/b1d25db9-4c3e-4d2b-8637-6153ecab5a46)

## Dependencies

~Based on https://github.com/netobserv/network-observability-console-plugin/pull/389~

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [x] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [x] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Comment by jpinsonneau** [comment]
Rebased with no changes

**Comment by jpinsonneau** [comment]
Rebased with no changes

**Comment by jpinsonneau** [comment]
As requested in https://issues.redhat.com/browse/NETOBSERV-1319 comments, I've added a tooltip: https://github.com/netobserv/network-observability-console-plugin/pull/405/commits/c58c40ae28769c84061f1845333e916ca0cf3df5

image
image

**Comment by jotak** [comment]
I'm seeing small glitches when testing:

Capture d’écran du 2023-11-20 11-57-58

1. When viewed on my laptop, the chart overlaps out of the page on the right (my laptop screen resolution is 1920x1080)
2. The scrollbar is located at the right, despite what's actually scrollable is the left pane, which is misleading because when your mouse is over the right pane and you try scrolling down it doesn't actually work, you need to go over the left pane to scroll. idk if it's an issue only in firefox, i didn't test with chrome.

I'm good to merge if you prefer and we add that to a new bug ticket ; because otherwise, LGTM

/lgtm

**Comment by jpinsonneau** [comment]
> 1. When viewed on my laptop, the chart overlaps out of the page on the right (my laptop screen resolution is 1920x1080)

I can't reproduce locally, however I pushed a commit to ensure the flex div doesn't wrap content
https://github.com/netobserv/network-observability-console-plugin/pull/405/commits/ea171bdaf031fbccaf543aa399d2415c4d752496
Does that solve your issue ?

> 2. The scrollbar is located at the right, despite what's actually scrollable is the left pane, which is misleading because when your mouse is over the right pane and you try scrolling down it doesn't actually work, you need to go over the left pane to scroll. idk if it's an issue only in firefox, i didn't test with chrome.

That's on all browers. I can suggest to switch focused panel on left and list on right as an easy fix :smile_cat: WDYT ?

**Review by jotak — APPROVED** [review]
/lgtm

**Pull request merged**
