### PR TITLE
NETOBSERV-1450: use isolated states for mobx

### PR DESCRIPTION
**Pull request by jotak**
## Description

As mobx is also used by the console itself, it must be configured as isolated to prevent conflicting versions.

## Dependencies

n/a

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [x] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [x] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Comment by memodi** [comment]
@jotak - I tried with the PR image, I still see the same exception. Let me know if you need cluster info.

**Comment by jotak** [comment]
@memodi did you clear the browser cache?

**Comment by memodi** [comment]
> @memodi did you clear the browser cache?

yes, it was a fresh load when I tried last and now also tried empty cache and hard reload multiple times, on every refresh I am seeing this error.

**Comment by jotak** [comment]
@memodi indeed I also still see the exception in the javascript console, however it seems like the page is now loading fine despite this error:
image
Isn't it the same for you?

I suspect the remaining error might be something wrong not on netobserv but on the console itself.

**Review by jpinsonneau — APPROVED** [review]
Code looks good, let's just ensure it works on all OCP versions

**Comment by memodi** [comment]
@jotak - last time when I had tested the error was still thrown, I know you were discussing this with console team -  has something changed since then to make error not occur?

**Pull request merged**
