### PR TITLE
NETOBSERV-79 Added ip addresses columns and special sorting for them

### PR DESCRIPTION
**Pull request by OlivierCazade**
Numerical sorting was already done, at the end this task was more about adding address columns and their sorting.

### CODE REVIEW

**Comment by OlivierCazade** [comment]
@jpinsonneau I think this PR will conflict with yours.

Since this one is very small we can wait to merge it if you want.

**Comment by OlivierCazade** [comment]
IMO we should have sorting functions in both backend and frontend.
- backend (or directly with loki) because if a user ask for refresh, we want to provide the last flows based on the current sorting column
- frontend because if a user wants to sort current row diffrently, we don't need to query the backend again.

**Comment by jpinsonneau** [comment]
I guess this will depend of how we are going to manage paging right ?

**Review by mariomac — APPROVED** [review]
/lgtm

**Pull request merged**
