### PR TITLE
NETOBSERV-1443 Console plugin loki timeout should be configurable

### PR DESCRIPTION
**Pull request by jpinsonneau**
## Description

This PR increase server write timeout if Loki one goes over.

## Dependencies

https://github.com/netobserv/network-observability-operator/pull/522

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [X] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [X] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Comment by jpinsonneau** [comment]
Since the queries could take more time than the selected refresh interval (up to 5 minutes), we should improve the `tick` mechanism to postpone next call right after the results being returned.

This is a corner case so we can merge as is but I'm looking for ways to do that in parallel.

**Review by jotak — APPROVED** [review]

**Comment by Amoghrd** [comment]
@jpinsonneau Could you rebase and remove the older ok-to-test label so that I can create a newer image for testing. TIA!

**Comment by jpinsonneau** [comment]
Updated branch and restored labels, the image is coming @Amoghrd !

**Pull request merged**
