### PR TITLE
NETOBSERV-101 R&D: Kube enricher write path for downstream operator

### PR DESCRIPTION
**Pull request by jpinsonneau**
This PR adds Authorization header to loki client from specified `loki-token-path`

### CODE REVIEW

**Review by mariomac — APPROVED** [review]
LGTM. Not tested it.

**Comment by jpinsonneau** [comment]
Thanks for your review @mariomac. I will wait for each PR of this story to be ready and tested before merge :+1:

**Review by OlivierCazade — APPROVED** [review]
The PR LGTM but instead of having a static token configuration, did you try using the dynamic plugin authorize feature?
https://github.com/openshift/enhancements/blob/master/enhancements/console/dynamic-plugins.md

My understanding is that we could benefits from user authentication to the console to get its token and have a per user authorization.

We can track this improvement in a new ticket if you want.

**Comment by jpinsonneau** [comment]
> The PR LGTM but instead of having a static token configuration, did you try using the dynamic plugin authorize feature? https://github.com/openshift/enhancements/blob/master/enhancements/console/dynamic-plugins.md
> 
> My understanding is that we could benefits from user authentication to the console to get its token and have a per user authorization.

I didn't tried yet but you are totally right ! In theory you could set users in the [ClusterRoleBinding](https://github.com/grafana/loki/blob/main/operator/docs/user-guides/forwarding_logs_to_gateway.md#forwarding-clients)

That would be useful mostly if we want to add a page in the developer view right ?
On admin side, I'm not sure we want to split the role per user; at least for now.

**Comment by OlivierCazade** [comment]
> I didn't tried yet but you are totally right ! In theory you could set users in the [ClusterRoleBinding](https://github.com/grafana/loki/blob/main/operator/docs/user-guides/forwarding_logs_to_gateway.md#forwarding-clients)
> 
> That would be useful mostly if we want to add a page in the developer view right ?
On admin side, I'm not sure we want to split the role per user; at least for now.

**Pull request merged**
