### PR TITLE
NETOBSERV-1733 fix url filters init / update

### PR DESCRIPTION
**Pull request by jpinsonneau**
## Description

Fix different scenarios where URL parameters are not correctly initialized / updated.

## Dependencies

n/a

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [X] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [X] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Review by jotak — APPROVED** [review]

**Comment by jpinsonneau** [comment]
@memodi @Amoghrd do you know why the `VK_ERROR_INCOMPATIBLE_DRIVER` error came back on cypress tests ? :thinking:

**Comment by Amoghrd** [comment]
I havent seen that error before

**Comment by memodi** [comment]
> @memodi @Amoghrd do you know why the `VK_ERROR_INCOMPATIBLE_DRIVER` error came back on cypress tests ? 🤔

@jpinsonneau it's just a warning, I don't think we ever got rid of that warning. Here the manage column tests failed at below assertion: 
```
       manage columns:
     AssertionError: Timed out retrying after 10000ms: Expected to find element: `#clear-all-filters-button`, but never found it.
      at reload (webpack://netobserv-plugin/./cypress/e2e/table/table.spec.ts:11:7)
      at Context.eval (webpack://netobserv-plugin/./cypress/e2e/table/table.spec.ts:48:4)
```

**Comment by jpinsonneau** [comment]
> > @memodi @Amoghrd do you know why the `VK_ERROR_INCOMPATIBLE_DRIVER` error came back on cypress tests ? 🤔
> 
> @jpinsonneau it's just a warning, I don't think we ever got rid of that warning. Here the manage column tests failed at below assertion:
> 
> ```
>        manage columns:
>      AssertionError: Timed out retrying after 10000ms: Expected to find element: `#clear-all-filters-button`, but never found it.
>       at reload (webpack://netobserv-plugin/./cypress/e2e/table/table.spec.ts:11:7)
>       at Context.eval (webpack://netobserv-plugin/./cypress/e2e/table/table.spec.ts:48:4)
> ```

Oh I missed that error thanks. So you probably have an issue in your cypress tests. 
You should clear the cache between each tests; else filters are reloaded from local storage and restored to their previous state (empty here).

**Comment by memodi** [comment]
> Oh I missed that error thanks. So you probably have an issue in your cypress tests. 

@Amoghrd do we?

You should clear the cache between each tests; else filters are reloaded from local storage and restored to their previous state (empty here).

@jpinsonneau we do clear localStorage https://github.com/openshift/openshift-tests-private/blob/master/frontend/views/netflow-page.ts#L4 as first thing before visting /netflow-traffic page :)

**Comment by Amoghrd** [comment]
I did not run the regression tests for this PR. But I did run for 1.6.1 release and other PR's and did not see any issues in our cypress tests

**Comment by memodi** [comment]
> I did not run the regression tests for this PR. But I did run for 1.6.1 release and other PR's and did not see any issues in our cypress tests

it may be worth to run regression tests pre-merge for this PR

**Comment by jpinsonneau** [comment]
cypress passed this time :smile:  https://github.com/netobserv/network-observability-console-plugin/pull/563/commits/eccd483053af5465c0d151ed8b108bd65acb63d5
merging now

**Comment by Amoghrd** [comment]
Ran regression tests https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/cypress-tests/735/console Some flakes but looks good overall

**Comment by jpinsonneau** [comment]
> Ran regression tests https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/cypress-tests/735/console Some flakes but looks good overall

Thanks !

**Pull request merged**
