### PR TITLE
NETOBSERV-636 UI Consistency: Overview styling

### PR DESCRIPTION
**Pull request by jpinsonneau**
Overview styling:
- background color
- flat card with flex title
- refactored spacing
- refactored chart sizing

Query summary:
- now full size, below page content
- flat card
- blue icon on limit exceded 
image
- see more / see less button
image

image
image
image

### CODE REVIEW

**Comment by jotak** [comment]
Thanks, the screenshots look great!
I'll test it now while I'm here

**Comment by jotak** [comment]
there's a problem with the dark theme:
image

**Comment by jotak** [comment]
It also partially addresses this ticket that I created: https://issues.redhat.com/browse/NETOBSERV-683 (the point on charts width)

**Review by andrew-ronaldson — APPROVED** [review]
LGTM but defer to engineer review.

**Comment by jpinsonneau** [comment]
> there's a problem with the dark theme

- Fixed background for dark theme:
image

- Also created a theme hook so it updates correctly our styling if you change theme from another tab https://github.com/netobserv/network-observability-console-plugin/pull/222/commits/5e7fa0fbe5a1cefe1d1a6f12fac404efa05c3850

**Review by jotak — APPROVED** [review]
LGTM!

**Pull request merged**
