### PR TITLE
NETOBSERV-1241 Back and forth show the opposite

### PR DESCRIPTION
**Pull request by jpinsonneau**
I'm suggesting to simply invert `back and forth` & `one way` texts. 
If it's not clear enough, we should think about a check box / a switch or a radio button instead

### CODE REVIEW

**Review by msherif1234 — COMMENTED** [review]
Can u explain pros vs cons for this change ?

**Comment by jpinsonneau** [comment]
I don't think there are cons here. Just a matter of better UX.

Currently when 'back and forth' is shown, it's actually one way:
image
And vice versa:
image

**Comment by jpinsonneau** [comment]
Merging this as it impacts other debuging / testings

**Pull request merged**
