### PR TITLE
NETOBSERV-871 UI: Connection tracking query option

### PR DESCRIPTION
**Pull request by jpinsonneau**
This PR implements connection tracking as query option
image

It also adds 2 new related columns:
- Connection Id
- Type

Listing connections:
image

Listing flows:
image

It also bring a filter capability on connection id:
image

And finally the ability to switch type and filter on a particular connection id from side panel:
image

image

### CODE REVIEW

**Comment by jpinsonneau** [comment]
renamed 'connection' to 'conversation' https://github.com/netobserv/network-observability-console-plugin/pull/285/commits/e264482177e759d06d48a66a18e21bf4614a308d and improved tooltips / column values display

image
image

**Comment by jpinsonneau** [comment]
[rename updateConnection -> heartbeat](https://github.com/netobserv/network-observability-console-plugin/pull/285/commits/79e9a43c01febe40e976e2cf30b045b3583370a2) + rebased

**Comment by jpinsonneau** [comment]
/unhold sync merge https://github.com/netobserv/network-observability-operator/pull/252 when both are ready
https://github.com/netobserv/flowlogs-pipeline/pull/387 is optionnal to remove duplicated count in connection infos

**Comment by jpinsonneau** [comment]
[As suggested](https://redhat-internal.slack.com/archives/C02939DP5L5/p1676971547474739) connection tracking is now optionnal.

**Comment by stleerh** [comment]
Code looks good! /lgtm

**Comment by jpinsonneau** [comment]
Addressed feedback on `ConnectionHeartbeatInterval` renaming +  `OutputRecordTypes` enum

**Pull request merged**
