### PR TITLE
NETOBSERV-1274 index duplicate (improve query perfs)

### PR DESCRIPTION
**Pull request by jotak**
Operator PR: https://github.com/netobserv/network-observability-operator/pull/409

### CODE REVIEW

**Review by jpinsonneau — APPROVED** [review]

**Comment by jotak** [comment]
thanks @jpinsonneau !
/approve

**Comment by jpinsonneau** [comment]
I'm flagging this PR as `breaking-change` here since it will display empty result if you update operator without these changes. The opposite should show an error since `Duplicate` was not a label.

**Pull request merged**
