### PR TITLE
NETOBSERV-384 Update deprecated console resource tab

### PR DESCRIPTION
**Pull request by jpinsonneau**
- Update deprecated `resource/tab`
- Added tabs
  - Route (from related `service`)
  - Node
  - ReplicaSet (from `owner ref`)
  - HorizontalPodAutoscaler (from `scale target`)
- Force maximum tab height

image

It seems that double scroll bar came back with latest console version in tabs. I have restored the `max-height` for this case.

### CODE REVIEW

**Comment by mariomac** [comment]
I have been testing it but I can't see any difference with the previous version. ¿Is that ok or should I see something different?

**Comment by jpinsonneau** [comment]
> I have been testing it but I can't see any difference with the previous version. ¿Is that ok or should I see something different?

You should see extra tabs:
- Route
- Node
- ReplicaSet
- HorizontalPodAutoscaler

**Comment by mariomac** [comment]
Ah thanks! I didn't find them.

Another question.This is the normal netflow table's filter:
image

The "embedded" filter seems to be more compact. Is this intended or are we missing a separation?

image

**Comment by jpinsonneau** [comment]
> The "embedded" filter seems to be more compact. Is this intended or are we missing a separation between both rows?

Yeah this was intended since tabs implementation.

Would you prefer something like this ?
image

**Comment by mariomac** [comment]
> Would you prefer something like this ?

Looks cleaner for me, but I understand that we want to save space.

**Review by mariomac — APPROVED** [review]

**Pull request merged**
