### PR TITLE
Fixed modified plugin proxy url

### PR DESCRIPTION
**Pull request by jotak**
Related to: https://bugzilla.redhat.com/show_bug.cgi?id=2041605

### CODE REVIEW

**Review by OlivierCazade — CHANGES_REQUESTED** [review]
Thanks.
We also need to uprade the make bridge target.

**Comment by jotak** [comment]
@OlivierCazade done

**Review by OlivierCazade — APPROVED** [review]
Thanks!

**Review by jpinsonneau — APPROVED** [review]

**Pull request merged**
