### PR TITLE
NETOBSERV-1551: show cross-nodes duplicates in merge mode

### PR DESCRIPTION
**Pull request by jotak**
## Description

This PR currently just shows the cross-nodes duplicates.

Following the reproduce steps described in [NETOBSERV-1551](https://issues.redhat.com//browse/NETOBSERV-1551), I'm now seeing both interfaces:
image

But they are displayed as distinct flows. So it raises the question: should we reintroduce the "Show duplicates" checkbox, since there are still the cross-nodes duplicates even in merge mode? Or should we merge them post-query without asking? If we do so, what to put in Node Direction? "both" ?

## Dependencies

n/a

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [ ] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [ ] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Comment by jpinsonneau** [comment]
I'm fine merging these flows without asking (or rename show duplicate to merge and enable by default :smile_cat: )
- `NodeDirection` should be kept as is since we are going to keep a single flow from a single node. 
  - Else it would require to keep node / agent info too ?
- `Ingress` can be the favorite as same as metrics queries https://github.com/netobserv/network-observability-console-plugin/blob/dc83aa0bfea89968f9e9e45705b5b35aec2e9966/pkg/model/filters/filters.go#L67-L91
- Interfaces and directions must be merged keeping the order `Egress` + `Ingress` in the array

**Comment by jotak** [comment]
(rebased)

**Comment by jotak** [comment]
Ok I added a commit that merges without asking.
I haven't changed anything about the Node Direction, ie. this is still whoever has more relevant information (DNS, PktDrops ...) that takes precedence, or else it just pick the first found. This part of the algorithm hasn't changed.

**Review by jpinsonneau — APPROVED** [review]
Looks good in terms of code. Thanks !

**Review by memodi — COMMENTED** [review]
@jotak I am seeing the interface directions column have n/a set when there are multiple directions, probably it should list multiple directions just the way interfaces are listed?

image

Env info:
```
OCP: 4.16.0-0.nightly-2024-03-13-061822
NetObserv operator: v0.0.0-22a1963
Loki: 0-click-loki
eBPF-agent: main
FLP: main
ConsolePlugin: b67f85f
```

**Comment by jotak** [comment]
@memodi I confirm the problem but also having the same problem on main branch (although it's harder to see because there isn't as many merged flows, but scrolling a little bit I can find some)
E.g:
image

Let me see if I can do a quick fix anyway...

**Comment by jotak** [comment]
@memodi last commit should fix it
cc @jpinsonneau

**Comment by memodi** [comment]
> although it's harder to see because there isn't as many merged flows, but scrolling a little bit I can find some

@jotak - I thought the flows with multiple interfaces and directions are the merged ones, no? (most ones that are shown in your screenshot)

**Comment by memodi** [comment]
I was able to verify we're not populating Directions column correctly:

image

/label qe-approved

**Comment by jotak** [comment]
> > although it's harder to see because there isn't as many merged flows, but scrolling a little bit I can find some
> 
> @jotak - I thought the flows with multiple interfaces and directions are the merged ones, no? (most ones that are shown in your screenshot)

True but there's 2 levels of merge: first in the agent (this was done by the previous "deduper-merge" PR already merged) but it cannot merge everything, so a second merge is done here with this PR.

**Pull request merged**
