### PR TITLE
NETOBSERV-1621: fix error messages

### PR DESCRIPTION
**Pull request by jpinsonneau**
## Description

This PR fixes multiple cases:
- when user is not authorized, error coming from `getConfig` was ignored
- added suggestions for `Lokistack` / `Manual` auth configurations
- when loki query is failing, `/ready` endpoint error is now displayed in console to avoid confusion
- when network issue is the root cause, it suggest to check connectivity

Also refactored the code to prepare for Prometheus datasource and added a `denyAll` checker for debugging

## Dependencies

n/a

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [X] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [X] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Comment by jotak** [comment]
on this particular point:

> when user is not authorized, error coming from getConfig was ignored

Isn't it on purpose? Or perhaps just accidental, but it seems logical that non-authorized users should not be able to get insights in the config

**Comment by jotak** [comment]
We will need to backport that

**Comment by jpinsonneau** [comment]
> on this particular point:
> 
> > when user is not authorized, error coming from getConfig was ignored
> 
> Isn't it on purpose? Or perhaps just accidental, but it seems logical that non-authorized users should not be able to get insights in the config

The frontend was not showing any error here which means it uses default config and run flow / metrics queries before getting the not authorized error.
When the user is not loggued in, first call to API must return an error (ie `/api/frontend-config` here).

**Comment by jpinsonneau** [comment]
Rebased but started to have issues with testing :thinking: 

I have added a fix to bypass the error when `getLokiReady` is not defined but I don't know why this happens now:
https://github.com/netobserv/network-observability-console-plugin/pull/523/commits/e9cbb12819024877f8e1b11533784e8197aebd9c

**Comment by jotak** [comment]
@memodi @jpinsonneau do you understand the cypress errors? Is that something requiring a change on the cypress test side?
I believe we want to have this fix in the release, don't we?

**Comment by jpinsonneau** [comment]
> @memodi @jpinsonneau do you understand the cypress errors? Is that something requiring a change on the cypress test side? I believe we want to have this fix in the release, don't we?

I seems to be related to prometheus enabled in the FlowCollector but not provided in the test cluster:
```
time="2024-06-03T07:14:27Z" level=error msg="Error in QueryMatrix" error="error from Prometheus query: Post \"http://prometheus:9090/api/v1/query_range\": dial tcp: lookup prometheus on 172.30.0.10:53: no such host" module=prometheus
```

**Comment by jotak** [comment]
tests pass \o/
/lgtm

**Comment by memodi** [comment]
thanks the test passes now, however a small issue UI issue now is - the Traffic flows is now greyed out even with Loki is enabled, it displays the correct error message though.

image

**Comment by jpinsonneau** [comment]
Rebased without changes

**Comment by jpinsonneau** [comment]
> thanks the test passes now, however a small issue UI issue now is - the Traffic flows is now greyed out even with Loki is enabled, it displays the correct error message though.
> 
> image

@memodi this tab is enabled only when Loki datasource is available. By default, none are available until the config is loaded for the configmap through the backend API.

If your user doesn't have the proper rights to load the content, the tab will be greyed out as we can't load the config either. Is that an issue for you ?

**Comment by memodi** [comment]
> @memodi this tab is enabled only when Loki datasource is available. By default, none are available until the config is loaded from the configmap through the backend API.
> 
> If your user doesn't have the proper rights to load the content, the tab will be greyed out as we can't load the config either. Is that an issue for you ?

@jpinsonneau in that case the information message is misleading, because in my case loki was enabled and it asks for loki to be enabled for Traffic flows tab.  I was hoping to Traffic flows will be consistently enabled like Topology and Overview tabs and this hasn't been issue until 1.5 release.

**Comment by jpinsonneau** [comment]
I can enable all datasources by default in that case so the view will be enabled until we check for config when the user has the proper rights

**Comment by memodi** [comment]
/label qe-approved
(based on testing for 1.6 backport)

**Pull request merged**
