### PR TITLE
NETOBSERV-1222: create PR template

### PR DESCRIPTION
**Pull request by jotak**

### CODE REVIEW

**Review by jpinsonneau — APPROVED** [review]
Looks good as first version !
Some ideas I have in mind for improvments:
- Guided tour / Tooltips help required
- Is feature gated / Automatically updated from config
- Screenshots attachement

**Comment by jotak** [comment]
@jpinsonneau I'll merge for now but can you elaborate on that? What do you mean by "guided tour" for instance? Screenshot attachment => you mean adding a new item to the checklist asking to attact screenshots when relevant?

/approve

**Comment by memodi** [comment]
> Some ideas I have in mind for improvments:
> 
> * Guided tour / Tooltips help required
> * Is feature gated / Automatically updated from config
> * Screenshots attachement

+1 on this for plugin these would be very helpful.

**Comment by jpinsonneau** [comment]
> - Guided tour / Tooltips help required

I usually forget to add guided tour while adding new features. Sometimes just some tooltips are good enough. 
We should be able to mark PRs for that

> - Is feature gated / Automatically updated from config

That's usefull for enablement. If something need to be hidden, such as 3D view, we need to provide the feature flag.
If it's automated it requires an operator PR

> - Screenshots attachement

Most of the time screens are better than words ☺️ but also super useful to come back on previous work and pick items to put in presentations.

**Pull request merged**
