### PR TITLE
Frontend formatting

### PR DESCRIPTION
**Pull request by jotak**
- Add pretty-quick / prettier
- update dockerfile/makefile for frontend formatting invoked before building
- run formatting

### CODE REVIEW

**Comment by jotak** [comment]
/hold
I've included it in build stage rather than pre-commit, however maybe that doesn't work when building after committing, let me check...

**Review by mariomac — APPROVED** [review]

**Review by OlivierCazade — APPROVED** [review]

**Comment by jotak** [comment]
@jpinsonneau added a `fix-import` npm script that runs as part of the frontend formatting

**Review by jpinsonneau — APPROVED** [review]
Works great on my side. Cool to see changed files highlighted :+1: 

Thanks @jotak

**Pull request merged**
