### PR TITLE
Add metrics to overview div

### PR DESCRIPTION
**Pull request by Amoghrd**

### CODE REVIEW

**Review by jpinsonneau — APPROVED** [review]
LGTM thanks @Amoghrd !

**Comment by Amoghrd** [comment]
Should we backport this to 1.3 release branch?
If not, will have to wait for 1.4 downstream builds to get this PR in the next downstream build right?

**Comment by jpinsonneau** [comment]
yes this has to be backported to have it in 1.3. I'm fine with that !

**Pull request merged**
