### PR TITLE
NETOBSERV-1227 NETOBSERV-1388: Max / P90 / P99 graphs

### PR DESCRIPTION
**Pull request by jpinsonneau**
## Description

Add functions for time based metrics (DNS Latency / RTT):
- [X] min
- [X] max
- [X] P90
- [X] P99

Related changes:
- [X] refactor of overview page / graphs
- [x] new metrics on topology labels
- [X] query summary
- [X] improved testing using a list of expected queries

These changes will also fix [NETOBSERV-1388](https://issues.redhat.com/browse/NETOBSERV-1388)

## Dependencies

Based on https://github.com/netobserv/network-observability-console-plugin/pull/405
Panel ids will need update in https://github.com/netobserv/network-observability-console-plugin/pull/424

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [x] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [x] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Comment by jpinsonneau** [comment]
@jotak & @OlivierCazade could you please take a look at this draft so we can validate the approach ?
I would like to confirm this approach fits our needs and is not too heavy to maintain.
If you have a lighter alternative in mind please let me know :smiley: 

Thanks !

**Comment by jpinsonneau** [comment]
> I think we should restrict these new charts to only latencies (RTT and DNS)

Sure, makes sense to me. I removed the new charts from rates ones and took the opportunity to save all the metrics in a single state so it will be easier to update in the future.
https://github.com/netobserv/network-observability-console-plugin/pull/412/commits/ae9bcf582093b22a57f9a3457210c7c24dae9bf9

image
image

**Comment by Amoghrd** [comment]
@jpinsonneau Could you rebase post NETOBSERV-1319 merge since you mention it depends on that and I cant patch 2 consolePlugin images while testing😅

**Comment by jotak** [comment]
done with the review, I've found just 2 issues, after that it's lgtm, nice work!

**Comment by jpinsonneau** [comment]
Thanks for your feedback @jotak !

It seems indeed that `DnsLatencyMs` contains zeros which was not expected:
```
  "DnsErrno": 0,
  "DnsFlags": 34048,
  "DnsFlagsResponseCode": "NoError",
  "DnsId": 64587,
  "DnsLatencyMs": 0,
```
That's why the graph were showing zeros on `bottomk` `min_over_time` queries. We should investigate why we get these zeros. In between I've added a filter on query side to ensure we get non zero DnsLatency as:
```
|~`"DnsLatencyMs`!~`DnsLatencyMs%22:0[,}]`
```

Also skipped the normalization for dns & rtt queries and forced `n/a` label where values are not available.

https://github.com/netobserv/network-observability-console-plugin/pull/412/commits/972c7a526d3b3b4b6d402a8011eae24e7d1134a4

> Also, a UX remark on the topology side-panel: as we are adding more metrics I find it not very convenient that the "metric type" setting is shared between topology view (graph edges) and that side panel. I didn't realize immediately that to see other metrics I had to go back in the advanced /display options. We could even show a bit more than just a single selected metric type. I can create a story to suggest an enhancement here, for another release.

Could you please create a followup for this ? I'm open to any suggestions here

**Comment by Amoghrd** [comment]
@jpinsonneau I still see the hole next to donut graphs, is that going to be fixed in another PR or in this itself?

Could also confirm the DNS metrics are now seen for all edge labels

**Review by jotak — APPROVED** [review]
/lgtm

**Pull request merged**
