### PR TITLE
updated jest + react + enable style-loader

### PR DESCRIPTION
**Pull request by jpinsonneau**
This is preparatory work for [NETOBSERV-71](https://issues.redhat.com/browse/NETOBSERV-71) & [NETOBSERV-75](https://issues.redhat.com/browse/NETOBSERV-75)

- Update jest version and fix slow tests by setting:
```
"maxWorkers": 1,
"globals": {
    "ts-jest": {
        "isolatedModules": true
    }
},
```

- Update react to version 17 (as same as console) to fix white screen of death

- Enable `style-loader` to load css files

### CODE REVIEW

**Review by OlivierCazade — APPROVED** [review]
/lgtm thanks !

**Review by mariomac — APPROVED** [review]

**Comment by jpinsonneau** [comment]
> /lgtm
> 
> White screen of death? smile

Yes :disguised_face: Actually having react 17 in the console and react 16 in the plugin made patternfly crash at some components events during startup. The entire page become white and there is no workaround.

**Comment by jotak** [comment]
ok, I guess they changed that very recently because I didn't notice before

**Comment by jpinsonneau** [comment]
we had that on table headers mouseover on small screen size (@OlivierCazade set wrap to avoid this one) and on tooltips without workaround this time

**Pull request merged**
