### PR TITLE
Fix parenthesis in help message

### PR DESCRIPTION
**Pull request by ronensc**

### CODE REVIEW

**Review by jpinsonneau — APPROVED** [review]
seems that we abused of copy / paste !

Thanks @ronensc !

**Comment by jotak** [comment]
welcome to the console @ronensc 😀

**Comment by ronensc** [comment]
Thanks 😊 
What should I do to make `tide` check pass?

**Comment by jpinsonneau** [comment]
> Thanks blush What should I do to make `tide` check pass?

As soon as you have `CI succeeded` + `LGTM label` from one approver, you can type `/approve` to automatically merge the PR

**Pull request merged**
