### PR TITLE
NETOBSERV-1833: decompose TCPflags bitfield

### PR DESCRIPTION
**Pull request by jotak**
## Description

Now it will always shows the list of TCP flags rather than a numeric value:

image

## Dependencies

n/a

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [x] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [x] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Review by jpinsonneau — APPROVED** [review]
LGTM, thanks @jotak

**Comment by jotak** [comment]
Hey @Amoghrd 
I checked this issue and it's not a regression, it has always been like that. Doing as you suggest would require us to have bitwise operation in Loki queries (e.g. queries matching `Flags & 16 == 0`) , that's not something we have ever done and I'm don't even think it is possible in LogQL. So I fear this is a limitation we have to live with.

**Comment by jpinsonneau** [comment]
We could actually have the parsing step before storage and change the TCP flags field to a string array as we do for `Interfaces` for example.
In that way we could filter on multiple values easilly.

WDYT ?

**Comment by jotak** [comment]
then maybe for another task, right? that would involve changes in FLP, and may have some little performance impact

**Comment by jotak** [comment]
merging before cutting branches, will have to be tested post-merge

**Pull request merged**
