### PR TITLE
NETOBSERV-637 UI Consistency: Topology styling

### PR DESCRIPTION
**Pull request by jpinsonneau**
Blocked by https://github.com/netobserv/network-observability-console-plugin/pull/215 & https://github.com/netobserv/network-observability-console-plugin/pull/222

- Filtering color
image

- Decorators sizing / placement
image
Old "info" decorator has been removed in favor of side panel for better UX

- Decorators tooltips
image
image
image

- Node background fix on dark theme
image

- Edges barely visible on dark theme
image

- Unknown / external square shape
image

### CODE REVIEW

**Comment by jotak** [comment]
awesome, looks much better with the dark theme!
/lgtm

**Comment by jpinsonneau** [comment]
> awesome, looks much better with the dark theme! /lgtm

:+1: I have rebased for merge. No changes on my side

**Pull request merged**
